[workspace]
members = [
    "tonlibjson-sys",
    "tonlibjson-client",
    "tonlibjson-jsonrpc",
    "ton-grpc"
]

[workspace.dependencies]
anyhow = "1.0"
tower = { version = "0.4", features = ["full"] }
tokio = { version = "1.26", features = ["full"] }
futures = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["serde_derive"] }
base64 = "0.21"
hex = "0.4"
tokio-stream = "0.1"
tracing-test = "0.2.4"
