[workspace]
resolver = "2"
members = [
    "tonlibjson-sys",
    "tonlibjson-client",
    "ton-grpc",
    "tvm-grpc"
]

[workspace.dependencies]
anyhow = { version = "1.0", features = ["backtrace"]}
tower = { version = "0.4", features = ["full"] }
tokio = { version = "1.33", features = ["full"] }
futures = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-futures = { version = "0.2.5", features = ["std", "std-future", "futures-03"]}
serde_json = "1.0"
serde = { version = "1.0", features = ["serde_derive"] }
base64 = "0.21"
hex = "0.4"
tokio-stream = { version = "0.1", features = ["sync"]}
tracing-test = "0.2.4"
async-stream = "0.3.5"
tonic = { version = "0.9", features = ["gzip"] }
tonic-reflection = "0.9"
tonic-health = "0.9"
tonic-build = "0.9"
prost = "0.11"
opentelemetry = { version = "0.19.0", features = ["rt-tokio", "metrics"] }
opentelemetry-otlp = { version = "0.12.0", features = ["metrics"] }
tracing-opentelemetry = "0.19.0"
