[package]
name = "ton-grpc"
version = "0.2.0"
edition = "2021"
authors = ["Andrei Kostylev <a.kostylev@pm.me>"]

[features]
default = []
testnet = ["tonlibjson-client/testnet"]

[dependencies]
tonlibjson-client = { path = "../tonlibjson-client" }
tokio = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }
tonic-health = { workspace = true }
prost = { workspace = true }
either = "1.9"
derive-new = "0.5.9"
clap = { version = "4.4.4", features = ["derive"] }
metrics-exporter-prometheus = "0.12.1"

[build-dependencies]
tonic-build = { workspace = true }
