[package]
name = "ton-grpc"
version = "0.1.0"
edition = "2021"
authors = ["Andrei Kostylev <a.kostylev@pm.me>"]

[dependencies]
tonlibjson-sys = { path = "../tonlibjson-sys", features = ["tonemulator"] }
tokio = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tonic = "0.8"
tonic-reflection = "0.6"
tonic-health = "0.8"
prost = "0.11"

[build-dependencies]
protobuf-src = "1.1.0+21.5"
tonic-build = "0.8"
