[package]
name = "ton-grpc"
version = "0.1.0"
edition = "2021"
authors = ["Andrei Kostylev <a.kostylev@pm.me>"]

[dependencies]
tonlibjson-sys = { path = "../tonlibjson-sys", features = ["tonemulator"] }
tonlibjson-client = { path = "../tonlibjson-client" }
tokio = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
base64 = { workspace = true }
tonic = "0.9"
tonic-reflection = "0.9"
tonic-health = "0.9"
prost = "0.11"
either = "1.8"

[build-dependencies]
tonic-build = "0.9"
