apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ton-grpc.fullname" . }}
  labels:
    {{- include "ton-grpc.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ton-grpc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ton-grpc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ton-grpc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - /bin/ton-grpc
            {{- if .Values.metrics.enabled }}
            - --enable-metrics
            {{- end }}
          ports:
            - name: http
              containerPort: 50052
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: 9000
              protocol: TCP
            {{- end }}
          env:
            {{- if .Values.tonConfigUrl }}
            - name: TON_CONFIG_URL
              value: {{ .Values.tonConfigUrl }}
            {{- end }}
            - name: RUST_LOG
              value: info
            - name: RUST_BACKTRACE
              value: "1"
            {{- if .Values.extraEnvs }}
              {{- toYaml .Values.extraEnvs | nindent 12 }}
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            grpc:
              port: 50052
          startupProbe:
            tcpSocket:
              port: http
            failureThreshold: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
