apiVersion: v1
kind: Service
metadata:
  name: {{ include "ton-grpc.fullname" . }}
  labels:
    {{- include "ton-grpc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - port: 9000
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "ton-grpc.selectorLabels" . | nindent 4 }}
