[target.x86_64-unknown-linux-gnu]
rustflags = "-Clinker-plugin-lto -Clinker=clang -Clink-arg=-fuse-ld=lld -Ctarget-feature=+crt-static -Clink-arg=-flto --cfg tokio_unstable"

[target.x86_64-apple-darwin]
rustflags = "-Clinker=clang"

[build]
target = "x86_64-unknown-linux-gnu"

[registries.crates-io]
protocol = "sparse"
