[package]
name = "ton-liteserver-client"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tl-parser = { path = "../tl-parser" }
anyhow = { workspace = true }
quote = "1.0"
syn = "2.0.58"
prettyplease = "0.2.17"
convert_case = "0.6.0"

[dependencies]
adnl-tcp = { path = "../adnl-tcp" }
tl-core = { path = "../tl-core" }
anyhow = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
dashmap = "5.5.3"
bytes = "1.6.0"
pin-project = "1.1.5"
futures = "0.3.30"
rand = "0.8.5"
tokio-stream = "0.1.15"
thiserror = "1.0.58"

[dev-dependencies]
hex = "0.4.3"
base64 = "0.22.0"
tracing-test = "0.2.4"
tracing-subscriber = "0.3.18"

[features]
testnet = []
