[package]
name = "ton-types"
version = "0.1.0"
edition = "2021"
authors = ["Andrei Kostylev <a.kostylev@pm.me>"]

[dependencies]
bytes = { workspace = true }
thiserror = { workspace = true }
hex = { workspace = true }
nom = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
