[package]
name = "tonlibjson-sys"
version = "0.1.5"
edition = "2021"
authors = ["Andrei Kostylev <a.kostylev@pm.me>"]

[dependencies]
libc = "0.2"
anyhow = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
cmake = "0.1"
pkg-config = "0.3"

[dev-dependencies]
procinfo = "0.4"

[features]
default = ["tonlibjson", "tonemulator"]
testnet = []
tonlibjson = []
tonemulator = []
