[package]
name = "tonlibjson-client"
version = "0.4.7"
edition = "2021"
authors = ["Andrei Kostylev <a.kostylev@pm.me>"]

[dependencies]
tonlibjson-sys = { path = "../tonlibjson-sys" }
tower = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true}
serde = { workspace = true }
serde_json = { workspace = true }
tokio-stream = { workspace = true }
base64 = { workspace = true }
hex = { workspace = true }
async-stream = { workspace = true }
quick_cache = { workspace = true }
dashmap = "5.5"
uuid = { version = "1.5", features = ["v4", "fast-rng", "serde"] }
pin-project = "1.1"
reqwest = { version = "0.11", features = ["rustls-tls", "trust-dns"], default-features = false }
config = { version = "0.13", default-features = false }
url = { version = "2.4", features = ["serde"] }
rand = "0.8"
itertools = "0.11"
derive-new = "0.5.9"
async-trait = "0.1.74"
tokio-retry = "0.3"
bytes = "1.5"
crc = "3.0.1"
metrics = "0.21.1"

[dev-dependencies]
tracing-test = { workspace = true }
serial_test = "2.0.0"

[features]
testnet = ["tonlibjson-sys/testnet"]
