[package]
name = "tonlibjson-client"
version = "0.1.0"
edition = "2021"
authors = ["Andrei Kostylev <a.kostylev@pm.me>"]

[dependencies]
tonlibjson-sys = { path = "../tonlibjson-sys" }
tower = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true}
serde = { workspace = true }
serde_json = { workspace = true }
serde-aux = "4.0.0"
tokio-stream = { workspace = true }
async-stream = "0.3"
dashmap = "5.4"
uuid = { version = "1.2", features = ["v4", "fast-rng", "serde"] }
pin-project = "1.0"
reqwest = { version = "0.11", features = ["rustls-tls", "trust-dns"], default-features = false }
config = { version = "0.13", default-features = false }
url = { version = "2.3", features = ["serde"] }
rand = "0.8"
itertools = "0.10"
derive-new = "0.5.9"
async-trait = "0.1.57"
tokio-retry = "0.3"

[dev-dependencies]
hex = { workspace = true }
base64 = { workspace = true }
tracing-test = { workspace = true }

[features]
testnet = ["tonlibjson-sys/testnet"]
