name: Check PR
on:
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - .github/workflows/charts-*
      - charts/**
      - .release-please-manifest.json
      - release-please-config.json
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pr-check:
    name: Run rust-clippy analyzing
    runs-on:
      group: "CPUBound"
    permissions:
      contents: read
      checks: write
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libsecp256k1-dev libsodium-dev
      - uses: arduino/setup-protoc@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.4
      - run: cargo build -v --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: ""
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
          CMAKE_C_COMPILER_LAUNCHER: "sccache"
          CMAKE_CXX_COMPILER_LAUNCHER: "sccache"
      - run: cargo build -v --target x86_64-unknown-linux-gnu --features testnet
        env:
          RUSTFLAGS: ""
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
          CMAKE_C_COMPILER_LAUNCHER: "sccache"
          CMAKE_CXX_COMPILER_LAUNCHER: "sccache"
      - uses: actions-rs/clippy-check@v1
        env:
          RUSTFLAGS: ""
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
          CMAKE_C_COMPILER_LAUNCHER: "sccache"
          CMAKE_CXX_COMPILER_LAUNCHER: "sccache"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --target x86_64-unknown-linux-gnu
